### ISSUE TITLE
how to test the  trained model？

### ISSUE THREAD

**Issue by hiredd** [yh-iro/Keras-TP-GAN#1]
how to test the  trained model？

**Comment by yh-iro** [comment]
please see the code and instruction in misc/demo.py

**Comment by hiredd** [comment]
@yh-iro  thank you very much for  your reply ，  i have  run the  misc/demo.py  but the result was not good ， just ok for  trained image。  have you test the non-trained images ？

**Comment by yh-iro** [comment]
Yes. As noted in README.md, generalization is not good as authors. I tried some mon trains image. Some are so so with worse resolution and some are collapsed. It is considered a kind of overfitting so I think one possible way is to use not fine tuned LCNN model. Also other hyper parameters like L2 regularization are not enough optimized yet.

**Comment by hiredd** [comment]
i see ，   thank you
